language: node_js

node_js:
  - "10"
cache:
  directories:
    - "node_modules"
services:
    - postgresql

install:
  - npm install
  - npm install -g coveralls

env:
  global:
  - NODE_ENV=test
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - npm run test:remote
  - nyc report --reporter=text-lcov > coverage.lcov && coveralls